import type { NextPage } from 'next';
import Head from 'next/head';
import { PostItem, Profile } from '../components';

import { Issues } from '../interfaces';
import { queryPostsFromIssues, renderProfileMarkdown } from '../utils';

interface BlogProps {
  issues: Issues;
  profile: string;
}

const Blog: NextPage<BlogProps> = (props: BlogProps) => {
  const { issues, profile } = props;
  return (
    <div>
      <Head>
        <title>yuqimao854</title>
        <meta name='description' content='Generated by yuqimao' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <div className='md:flex justify-between'>
          <Profile profile={profile} />

          <div className='  basis-7/12 lg:px-16 lg:py-24  sm:py-12 sm:px-12  '>
            <div className=' group  '>
              <div className=' lg:grid grid-cols-2 gap-4   '>
                {issues.nodes.map((item) => {
                  return <PostItem {...item} key={item.id} />;
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export const getServerSideProps = async () => {
  // Fetch data from external API

  const [
    {
      repository: { issues },
    },
    { data: profile },
  ] = await Promise.all([
    await queryPostsFromIssues(),
    await renderProfileMarkdown(),
  ]);

  // Pass data to the page via props
  return { props: { issues: issues, profile } };
};

export default Blog;
