import type { NextPage } from 'next';
import Head from 'next/head';
import { PostItem, Profile } from 'components';

import { Issues } from 'interfaces';
import { queryPostsFromIssues, renderProfileMarkdown } from 'utils';

interface BlogProps {
  issues: Issues;
  profile: string;
}

const Blog: NextPage<BlogProps> = (props: BlogProps) => {
  const { issues, profile } = props;
  return (
    <div>
      <Head>
        <title>yuqimao854</title>
        <meta name='description' content='Generated by yuqimao' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <div className='relative '>
          <Profile profile={profile} />

          <div className=' lg:w-[60vw]  lg:absolute lg:right-0  xl:px-16 xl:py-24  lg:py-20 lg:px-12  '>
            <div className=' group  '>
              <div className=' xl:grid  xl:grid-cols-2 xl:gap-4   '>
                {[...issues.nodes].map((item) => {
                  return <PostItem {...item} key={item.id} />;
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export const getServerSideProps = async () => {
  // Fetch data from external API

  const [
    {
      repository: { issues },
    },
    { data: profile },
  ] = await Promise.all([
    await queryPostsFromIssues(),
    await renderProfileMarkdown(),
  ]);

  // Pass data to the page via props
  return { props: { issues: issues, profile } };
};

export default Blog;
