import { graphql } from 'graphql'
import type { NextPage } from 'next'
import Head from 'next/head'
import { queryPostsFromIssues } from '../utils'


const Blog: NextPage = (props) => {
  console.log(props)
  return (
    <div>
      <Head>
        <title>yuqimao854</title>
        <meta name="description" content="Generated by yuqimao" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div> 我是首页 blog blog blog</div>
    </div>
  )
}



export const     getServerSideProps   = async ()=> {
  // Fetch data from external API

  const res =   await queryPostsFromIssues()

  // Pass data to the page via props
  return { props: { issues:res.repository.issues } }
}

export default Blog